// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// R_maxima_search
IntegerVector R_maxima_search(NumericMatrix xy, NumericVector z, double eps);
RcppExport SEXP _localmaximas_R_maxima_search(SEXP xySEXP, SEXP zSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(R_maxima_search(xy, z, eps));
    return rcpp_result_gen;
END_RCPP
}
// localmaximas_get_coordinates
SEXP localmaximas_get_coordinates(SEXP sxpHandle);
RcppExport SEXP _localmaximas_localmaximas_get_coordinates(SEXP sxpHandleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sxpHandle(sxpHandleSEXP);
    rcpp_result_gen = Rcpp::wrap(localmaximas_get_coordinates(sxpHandle));
    return rcpp_result_gen;
END_RCPP
}
// get_heights
Rcpp::NumericVector get_heights(SEXP sxpHandle);
RcppExport SEXP _localmaximas_get_heights(SEXP sxpHandleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sxpHandle(sxpHandleSEXP);
    rcpp_result_gen = Rcpp::wrap(get_heights(sxpHandle));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_localmaximas_R_maxima_search", (DL_FUNC) &_localmaximas_R_maxima_search, 3},
    {"_localmaximas_localmaximas_get_coordinates", (DL_FUNC) &_localmaximas_localmaximas_get_coordinates, 1},
    {"_localmaximas_get_heights", (DL_FUNC) &_localmaximas_get_heights, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_localmaximas(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
