# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_maxima_search <- function(xy, z, eps) {
    .Call('_localmaximas_R_maxima_search', PACKAGE = 'localmaximas', xy, z, eps)
}

localmaximas_get_coordinates <- function(sxpHandle) {
    .Call('_localmaximas_localmaximas_get_coordinates', PACKAGE = 'localmaximas', sxpHandle)
}

get_heights <- function(sxpHandle) {
    .Call('_localmaximas_get_heights', PACKAGE = 'localmaximas', sxpHandle)
}

