# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FindLocalMaxima <- function(handles, radius) {
    .Call('_localmaximas_FindLocalMaxima', PACKAGE = 'localmaximas', handles, radius)
}

SearchNeighbours <- function(xy, z, eps) {
    .Call('_localmaximas_SearchNeighbours', PACKAGE = 'localmaximas', xy, z, eps)
}

