# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_get_coordinates <- function(sxpHandle) {
    .Call('_localmaximas_test_get_coordinates', PACKAGE = 'localmaximas', sxpHandle)
}

test_get_heights <- function(sxpHandle) {
    .Call('_localmaximas_test_get_heights', PACKAGE = 'localmaximas', sxpHandle)
}

test_index_missing <- function(sxpHandle, sxpHeights) {
    .Call('_localmaximas_test_index_missing', PACKAGE = 'localmaximas', sxpHandle, sxpHeights)
}

R_maxima_search <- function(xy, z, eps) {
    .Call('_localmaximas_R_maxima_search', PACKAGE = 'localmaximas', xy, z, eps)
}

